// UIラベル定数
window.UILabels = {
    // 通知メッセージ
    SAVED: '保存しました',
    AUTO_SAVED: '自動保存されました',
    RESTORED: 'バックアップから復元しました',
    BACKUP_SAVED: 'バックアップを保存しました',
    IMAGE_INSERTED: '画像を挿入しました',
    CHOICE_BLOCK_INSERTED: '選択肢ブロックを挿入しました',
    LABEL_INSERTED: 'ラベルを挿入しました',
    JUMP_INSERTED: 'ジャンプを挿入しました',
    // ボタンラベル
    SAVE: '保存',
    CANCEL: 'キャンセル',
    DELETE: '削除',
    EDIT: '編集',
    RESTORE: '復元',
    INSERT: '挿入',
    EXPORT: 'エクスポート',
    IMPORT: 'インポート',
    // その他
    CONFIRM_DELETE: '削除しますか？',
    CONFIRM_RESTORE: 'このバックアップで本文を置き換えます。よろしいですか？',
    UNSAVED_CHANGES_GENERIC: '未保存の変更があります。続行しますか？',
    UNSAVED_CHANGES_SWITCH: '未保存の変更があります。ファイルを切り替えますか？\n現在の内容はスナップショットとして自動退避します。',
    UNSAVED_CHANGES_NEW: '未保存の変更があります。新規作成を続行しますか？\n現在の内容はスナップショットとして自動退避します。',
    RESTORE_LAST_SNAPSHOT_CONFIRM: '最後のスナップショットから復元しますか？\n現在の内容はスナップショットとして保存されます。',
    RESTORE_NO_BACKUPS: '復元できるバックアップがありません',
    RESTORE_FAILED: '復元に失敗しました',
    CONFIRM_LOADOUT_DELETE: '選択中のロードアウトを削除しますか？',
    ACTIVE_LOADOUT_DELETE: 'アクティブなロードアウトは削除できません',
    LOADOUT_NAME_PROMPT: 'ロードアウト名を入力してください',
    LOADOUT_SAVED: 'ロードアウトを保存しました',
    LOADOUT_SELECT_TO_DUPLICATE: '複製するロードアウトを選択してください',
    LOADOUT_DUPLICATE_SUFFIX: ' (複製)',
    LOADOUT_DUPLICATED: 'ロードアウトを複製しました',
    LOADOUT_APPLIED: 'ロードアウトを適用しました',
    LOADOUT_DELETE_CONFIRM: 'このロードアウトを削除しますか？',
    LOADOUT_DELETED: 'ロードアウトを削除しました',
    DUPLICATE_LOADOUT_NAME: '複製先の名前を入力してください',
    BASE_LOADOUT_NAME: '複製元のロードアウトを選択してください',
    CAPTURE_FAILED: '現在の構成を取得できませんでした',
    NO_NAME: '名前を入力してください',
    // プレースホルダー
    LABEL_ID_PROMPT: 'ラベルIDを入力',
    JUMP_LABEL_PROMPT: 'ジャンプ先ラベルIDを入力',
    WIKI_TITLE_PROMPT: 'Wikiページのタイトルを入力:',
    // ステータス
    OFFLINE: 'オフラインになりました。変更はローカルに保存されます。',
    ONLINE: 'オンラインに戻りました。',
    NO_BACKUPS: 'バックアップはありません',
    NO_IMAGES: '画像はまだ挿入されていません。画像を貼り付けるとここに一覧表示されます。',
    NO_WIKI_PAGES: 'Wikiページはまだありません。新規作成してください。',
    SEARCH_NO_RESULTS: '検索結果が見つかりません。',
    // ガジェットタイトル
    GADGET_CLOCK: '時計',
    GADGET_GOAL: '執筆目標',
    GADGET_BACKUP: 'バックアップ',
    GADGET_CHOICE: '選択肢',
    GADGET_PRINT: 'エクスポート',
    GADGET_IMAGES: '画像',
    GADGET_THEME: 'テーマ & フォント',
    GADGET_LAYOUT: 'エディタレイアウト',
    GADGET_HUD: 'HUD設定',
    GADGET_VISUAL_PROFILE: 'Visual Profile',
    // プロファイル関連
    PROFILE_LABEL: 'プロファイル',
    PROFILE_BUILTIN: '組み込み',
    PROFILE_USER_DEFINED: 'ユーザー定義',
    PROFILE_APPLY_TOOLTIP: '選択したプロファイルを適用',
    PROFILE_SAVE_TOOLTIP: '現在の設定を新規プロファイルとして保存',
    PROFILE_DELETE_TOOLTIP: 'ユーザー定義プロファイルを削除',
    PROFILE_NAME_PROMPT: 'プロファイル名を入力してください:',
    PROFILE_DELETE_CONFIRM: 'プロファイル「{name}」を削除しますか？',
    PROFILE_CURRENT: '現在: ',
    PROFILE_NOT_SET: '現在: 未設定',
    APPLY: '適用',
    DUPLICATE: '複製',
    // その他
    FEEDBACK_TITLE: 'フィードバック',
    FEEDBACK_PROMPT: '問題報告や機能要望をお送りください。',
    HUD_TEST: 'HUDテスト表示',
    CLEAR_GOAL: '目標をクリア',
    NOW_SAVE: '今すぐ保存',
    PRINT_PREVIEW: '印刷プレビュー',
    TXT_EXPORT: 'TXTエクスポート',
    ADD_URL: 'URL追加',
    EDIT_PROPERTIES: 'プロパティ編集',
    SHOW: '表示する',
    HIDE: '隠す',
    OPEN_TAB: '別タブで開く',
    NEW_WIKI_PAGE: '+ 新規Wikiページ',
    SEARCH_WIKI: 'Wikiページを検索...',
    CHOICE_BLOCK: '選択肢ブロック',
    LABEL: 'ラベル',
    JUMP: 'ジャンプ',
    // 設定ラベル
    FONT_FAMILY: 'フォントファミリー',
    FONT_SIZE: 'フォントサイズ',
    LINE_HEIGHT: '行間',
    UI_FONT_SIZE: 'UIフォントサイズ',
    EDITOR_FONT_SIZE: 'エディタフォントサイズ',
    BACKGROUND_COLOR: '背景色',
    TEXT_COLOR: '文字色',
    RESET_COLORS: '色をリセット',
    SHOW_BORDER: '枠線を表示',
    SHOW_PREVIEW: '画像プレビューを表示',
    EDITOR_PADDING: '執筆エリア内余白 (px)',
    HUD_POSITION: '表示位置',
    HUD_DURATION: '表示時間（ms）',
    HUD_BACKGROUND: '背景色',
    HUD_TEXT_COLOR: '文字色',
    HUD_OPACITY: '不透明度',
    HUD_WIDTH: '幅（px）',
    HUD_FONT_SIZE: 'フォントサイズ（px）',
    GOAL_TARGET: '目標文字数',
    DEADLINE: '締切日',
    SNAPSHOT_INTERVAL: '自動バックアップ間隔（ms）',
    SNAPSHOT_DELTA: '変更量（文字数）',
    SNAPSHOT_RETENTION: '保持数',
    PREVIEW_SYNC_SCROLL: '同期スクロール',
    AUTO_SAVE_ENABLED: '自動保存を有効',
    AUTO_SAVE_DELAY: '自動保存遅延（ms）',
    TYPEWRITER_ENABLED: 'タイプライターモード',
    TYPEWRITER_ANCHOR: 'アンカー位置',
    TYPEWRITER_STICKINESS: '追従度',
    WRAP_COLUMNS: '折り返し桁数',
    // 位置オプション
    POSITION_BOTTOM_LEFT: '左下',
    POSITION_BOTTOM_RIGHT: '右下',
    POSITION_TOP_LEFT: '左上',
    POSITION_TOP_RIGHT: '右上',
    ALIGNMENT_LEFT: '左寄せ',
    ALIGNMENT_CENTER: '中央',
    ALIGNMENT_RIGHT: '右寄せ',
    ALIGNMENT_AUTO: '自動',
    // 24時間表示
    HOUR_24: '24時間表示',

    // 追加UIラベル
    GADGET_SETTINGS: '',
    LOADOUT_LABEL: 'ロードアウト',
    PRESET_NAME_PLACEHOLDER: 'プリセット名',
    THEME_SECTION: 'テーマ',
    THEME_LIGHT: 'ライト',
    THEME_DARK: 'ダーク',
    THEME_SEPIA: 'セピア',
    TYPEWRITER_SECTION: 'タイプライターモード',
    AUTO_SAVE_SECTION: '自動保存',
    SNAPSHOT_SECTION: 'オートセーブ & スナップショット',
    EDITOR_SETTINGS_SECTION: 'エディタ設定',
    FILE_MANAGEMENT_SECTION: 'ファイル管理',
    CURRENT_FILE: '現在のファイル',
    NEW_FILE: '新規ファイル',
    RESTORE_FROM_BACKUP: '復元',
    HELP_SECTION: 'ヘルプ / リファレンス',
    OPEN_WIKI_HELP: 'Wikiヘルプを開く',
    EDITOR_GUIDE: 'エディタ機能ガイド',
    UI_LAB: 'UIレイアウト実験',
    QUICK_TOOLS: 'クイックツール',
    EDITOR_FONT: 'エディタフォント',
    HUD_CONTROL: 'HUD コントロール',
    HUD_TOGGLE: 'HUD表示/非表示',
    HUD_PIN: 'HUDピン固定',
    HUD_REFRESH: 'HUD再表示',
    SEARCH_REPLACE: '検索と置換',
    SEARCH_PLACEHOLDER: '検索するテキスト',
    REPLACE_PLACEHOLDER: '置換するテキスト',
    CASE_SENSITIVE: '大文字/小文字を区別',
    REGEX: '正規表現',
    REPLACE_ALL: 'すべて置換',
    PREV: '前へ',
    NEXT: '次へ',
    TEXT_ANIMATION: 'テキストアニメーション',
    FONT_DECORATION: 'フォント装飾',
    CLOSE: '閉じる',
    APPLY: '適用',
    DUPLICATE: '複製',

    // HUD動的ラベル
    HUD_SHOW: 'HUDを表示',
    HUD_HIDE: 'HUDを隠す',
    HUD_PIN_OFF: 'HUDピン解除',

    // Outline Gadget
    OUTLINE_UNAVAILABLE: 'アウトライン機能を利用できません。',
    OUTLINE_DEFAULT_SET_NAME: '部・章・節',
    OUTLINE_PART: '部',
    OUTLINE_CHAPTER: '章',
    OUTLINE_SECTION: '節',
    PRESET_LABEL: 'プリセット',
    CREATE_NEW_PRESET: '+ 新規',
    NAME_LABEL: '名前',
    PRESET_NAME_EXAMPLE: '例: 三部構成',
    LEVELS_CSV_LABEL: 'レベル（カンマ区切り）',
    LEVELS_CSV_PLACEHOLDER: '部,章,節',
    CREATE: '作成',
    MOVE_UP: '上へ',
    MOVE_DOWN: '下へ',
    INSERT_SUFFIX: ' を挿入',
    TITLE_SUFFIX: ' タイトル\n\n',
    NEW_PRESET_DEFAULT_NAME: '新規プリセット',
    LEVELS_CSV_REQUIRED: 'レベル名をカンマ区切りで入力してください',
    OUTLINE_INIT_FAILED: 'アウトラインの初期化に失敗しました。',
    GADGET_OUTLINE_TITLE: 'アウトライン',

    // Documents Gadget
    DOCS_STORAGE_UNAVAILABLE: 'ストレージ機能が利用できないため、ドキュメントを管理できません。',
    DEFAULT_DOC_NAME: 'ドキュメント1',
    NO_DOCUMENTS: '(なし)',
    UNTITLED_DOC: '無題',
    DOC_OPENED_MSG: '「{0}」を開きました',
    NEW_DOC_PROMPT: '新しいドキュメント名を入力',
    DOC_CREATED_MSG: 'ドキュメントを作成しました',
    RENAME_DOC_PROMPT: 'ドキュメント名を変更',
    DOC_RENAMED_MSG: 'ドキュメント名を更新しました',
    DELETE_DOC_CONFIRM: 'このドキュメントを削除しますか？この操作は元に戻せません。',
    DOC_DELETED_MSG: 'ドキュメントを削除しました',
    EDITOR_NEW_DOC_CONFIRM: '現在の内容を破棄して新規ドキュメントを作成しますか？',
    FILE_IMPORTED_MSG: 'ファイルを読み込みました',
    FILE_IMPORT_ERROR: 'ファイル読み込みエラー',
    DOC_LIST_LABEL: 'ドキュメント',
    RENAME: '改名',
    IMPORT_FILE: '読込',
    EXPORT_TEXT: 'TXT保存',
    EXPORT_MARKDOWN: 'MD保存',
    PRINT: '印刷',
    EXPORT_PDF: 'PDF',
    DOCS_INIT_FAILED: 'ドキュメントガジェットの初期化に失敗しました。',
    GADGET_DOCUMENTS_TITLE: 'ドキュメント',

    // Outline Quick Gadget
    STORAGE_UNAVAILABLE: 'ストレージが利用できません。',
    OUTLINE_LEVEL_1: '大見出し',
    OUTLINE_LEVEL_2: '中見出し',
    OUTLINE_LEVEL_3: '小見出し',
    OUTLINE_LEVEL_4: '詳細',
    OUTLINE_LEVEL_5: 'メモ',
    OUTLINE_LEVEL_6: '注記',
    COLLAPSE: '折りたたみ',
    EXPAND: '展開',
    SETTINGS: '設定',
    OPEN_SETTINGS: '設定を開く',
    OUTLINE_QUICK_INIT_FAILED: 'アウトラインガジェットの初期化に失敗しました。',
    GADGET_OUTLINE_QUICK_TITLE: 'クイックアウトライン',

    // Typography Themes Gadget
    TYPO_SETTINGS_UNAVAILABLE: 'タイポ設定を読み込めません。',
    THEME_NAME_LIGHT: 'ライト',
    THEME_NAME_DARK: 'ダーク',
    THEME_NAME_SEPIA: 'セピア',
    THEME_NAME_HIGH_CONTRAST: '高コントラスト',
    THEME_NAME_SOLARIZED: 'ソラリゼド',
    CUSTOM_COLOR_SECTION: 'カスタム色',
    COLOR_SECTION: '色',
    FONT_SECTION: 'フォント',
    BODY_FONT_SIZE: '本文フォントサイズ',
    FONT_SIZE_PREFIX: 'フォントサイズ: ',
    UI_FONT_SIZE_PREFIX: 'UIフォントサイズ: ',

    // Typography Gadget
    EDITOR_FONT_SIZE_PREFIX: 'エディタフォントサイズ: ',
    LINE_HEIGHT_PREFIX: '行間: ',
    TYPO_INIT_FAILED: 'タイポ設定ガジェットの初期化に失敗しました。',
    GADGET_THEME_TITLE: 'テーマ & フォント',

    // HUD Gadget
    HUD_SETTINGS_UNAVAILABLE: 'HUD設定は利用できません。',
    HUD_OPACITY_PREFIX: '不透明度: ',
    HUD_INIT_FAILED: 'HUD設定ガジェットの初期化に失敗しました。',
    GADGET_HUD_TITLE: 'HUD設定',

    // Goal Gadget
    GOAL_STORAGE_UNAVAILABLE: 'ストレージが利用できないため目標を保存できません。',
    GOAL_TARGET_PLACEHOLDER: '例: 2000',
    CLEAR_GOAL_CONFIRM: '執筆目標をクリアしますか？',
    GOAL_INIT_FAILED: '執筆目標ガジェットの初期化に失敗しました。',
    GADGET_GOAL_TITLE: '執筆目標',

    // Snapshot Gadget
    SNAPSHOT_UNAVAILABLE: 'スナップショット機能が利用できません。',
    CHARS_SUFFIX: ' 文字',
    SNAPSHOT_INIT_FAILED: 'スナップショットガジェットの初期化に失敗しました。',
    GADGET_BACKUP_TITLE: 'バックアップ',
    BACKUP_UNAVAILABLE: 'バックアップ機能を利用できません。',

    // Print Gadget
    PRINT_INIT_FAILED: '印刷設定ガジェットの初期化に失敗しました。',
    GADGET_EXPORT_TITLE: 'エクスポート',
    PRINT_PREVIEW: '印刷プレビュー',
    TXT_EXPORT: 'TXTエクスポート',
    EXPORT_FILENAME_DEFAULT: 'document.txt',

    // Choice Tools Gadget
    CHOICE_BLOCK_TITLE: '選択肢',
    CHOICE_OPTION_1: '選択肢1',
    CHOICE_OPTION_2: '選択肢2',
    CHOICE_INSERTED: '選択肢ブロックを挿入しました',
    LABEL_ID_PROMPT: 'ラベルIDを入力',
    LABEL_INSERTED: 'ラベルを挿入しました',
    JUMP_ID_PROMPT: 'ジャンプ先ラベルIDを入力',
    JUMP_INSERTED: 'ジャンプを挿入しました',
    BTN_CHOICE_BLOCK: '選択肢ブロック',
    BTN_LABEL: 'ラベル',
    BTN_JUMP: 'ジャンプ',
    CHOICE_TOOL_INIT_FAILED: '選択肢ツールの初期化に失敗しました。',
    GADGET_CHOICE_TITLE: '選択肢',

    // Images Gadget
    IMG_URL_PLACEHOLDER: '画像URLを入力',
    BTN_ADD_URL: 'URL追加',
    IMG_ALT_PLACEHOLDER: 'Altテキスト',
    IMG_WIDTH_LABEL: '幅 (px)',
    IMG_ALIGN_LABEL: '配置',
    BTN_SAVE: '保存',
    BTN_CANCEL: 'キャンセル',
    BTN_EDIT: '編集',
    BTN_EDIT_TITLE: 'プロパティ編集',
    BTN_DELETE: '削除',
    IMG_INIT_FAILED: '画像ガジェットの初期化に失敗しました。',
    GADGET_IMAGES_TITLE: '画像',

    // Editor Layout Gadget
    LAYOUT_WIDTH_PREFIX: '幅: ',
    LAYOUT_PADDING_PREFIX: '左右余白: ',
    LAYOUT_SHOW_BORDER: '枠線を表示',

    // Clock Gadget
    CLOCK_24H: '24時間表示',

    // Story Wiki Gadget
    WIKI_SEARCH_PLACEHOLDER: 'Wikiページを検索...',
    BTN_NEW_WIKI_PAGE: '+ 新規Wikiページ',
    WIKI_TITLE_PROMPT: 'Wikiページのタイトルを入力:',
    WIKI_NO_RESULTS: '検索結果が見つかりません。',
    WIKI_EMPTY: 'Wikiページはまだありません。新規作成してください。',
    WIKI_DELETE_CONFIRM: 'このWikiページを削除しますか？',
    WIKI_LABEL_TITLE: 'タイトル:',
    WIKI_LABEL_CONTENT: '内容:',
    WIKI_LABEL_TAGS: 'タグ:',
    WIKI_TAGS_PLACEHOLDER: 'タグ（カンマ区切り）',
    WIKI_INIT_FAILED: 'Wikiガジェットの初期化に失敗しました。',
    GADGET_WIKI_TITLE: '物語Wiki',

    // HUD Settings (Detailed)
    HUD_MESSAGE_LABEL: 'メッセージ:',
    HUD_MESSAGE_PLACEHOLDER: 'HUDに表示するメッセージ',
    HUD_PINNED_LABEL: '常に表示',
    BTN_SAVE_SETTINGS: '設定を保存',
    HUD_SAVED_MESSAGE: 'HUD設定を保存しました',

    // Sidebar Tabs / UI Settings
    TAB_NAME_REQUIRED: 'タブ名を入力してください',
    TAB_ADDED: 'タブを追加しました',
    TAB_RENAMED: '名称を変更しました',
    TAB_DELETE_CONFIRM: '削除しますか？',
    TAB_DELETED: '削除しました',

    // Loadout UI
    LOADOUT_TITLE: 'ロードアウト',
    LOADOUT_PLACEHOLDER: 'プリセット名を入力...',
    LOADOUT_SAVE: '保存',
    LOADOUT_DUPLICATE: '複製',
    LOADOUT_APPLY: '適用',
    LOADOUT_DELETE: '削除',

    // UI Modes
    MODE_NORMAL: '通常モード',
    MODE_FOCUS: 'フォーカスモード',
    MODE_BLANK: 'ブランクモード',
    MODE_TITLE: '表示モード',
    LOADOUT_NAME_PROMPT: 'ロードアウト名を入力してください',
    LOADOUT_SAVED: 'ロードアウトを保存しました',
    LOADOUT_DUPLICATE_SUFFIX: ' (複製)',
    LOADOUT_DUPLICATED: 'ロードアウトを複製しました',
    LOADOUT_SELECT_TO_DUPLICATE: '複製するロードアウトを選択してください',
    LOADOUT_SELECT_TO_APPLY: '適用するロードアウトを選択してください',
    LOADOUT_APPLIED: 'ロードアウトを適用しました',
    LOADOUT_APPLY_FAILED: 'ロードアウトの適用に失敗しました',
    LOADOUT_SELECT_TO_DELETE: '削除するロードアウトを選択してください',
    LOADOUT_DELETE_CONFIRM: 'このロードアウトを削除しますか？この操作は元に戻せません。',
    LOADOUT_DELETED: 'ロードアウトを削除しました',
    LOADOUT_DELETE_FAILED: 'ロードアウトの削除に失敗しました',

    // Index.html specific
    GOAL_TARGET_PLACEHOLDER: '目標文字数',
    EDITOR_PLACEHOLDER: 'ここに小説を入力してください...',

    // Font Decoration Titles
    DECOR_BOLD_TITLE: '太字 (Ctrl+B)',
    DECOR_ITALIC_TITLE: '斜体 (Ctrl+I)',
    DECOR_UNDERLINE_TITLE: '下線',
    DECOR_STRIKE_TITLE: '取り消し線',
    DECOR_BLACK_TITLE: '極太',
    DECOR_LIGHT_TITLE: '細字',
    DECOR_SMALLCAPS_TITLE: 'スモールキャップ',
    DECOR_SHADOW_TITLE: '影付き',
    DECOR_OUTLINE_TITLE: '輪郭',
    DECOR_GLOW_TITLE: '発光',
    DECOR_UPPERCASE_TITLE: '大文字',
    DECOR_LOWERCASE_TITLE: '小文字',
    DECOR_CAPITALIZE_TITLE: '先頭大文字',
    DECOR_WIDE_TITLE: '文字間広',
    DECOR_NARROW_TITLE: '文字間狭',

    // Text Animation Titles
    ANIM_FADE_TITLE: 'フェードイン',
    ANIM_SLIDE_TITLE: 'スライドイン',
    ANIM_TYPE_TITLE: 'タイプライター',
    ANIM_PULSE_TITLE: 'パルス',
    ANIM_SHAKE_TITLE: 'シェイク',
    ANIM_BOUNCE_TITLE: 'バウンス',
    ANIM_FADEIN_TITLE: 'ゆっくりフェード',

    // Hints
    HINT_FONT_SIZE_SHORTCUT: 'ショートカット: Ctrl/⌘ + (+ / - / 0)',
    HINT_HUD_PIN: 'ピン固定はローカル設定に保存されます。',
    HINT_SEARCH_SHORTCUT: 'ショートカット: Ctrl+F で検索パネルを開く',
    HINT_DECORATION: 'テキストを選択してボタンをクリック、またはタグを手動入力<br>例: [bold]テキスト[/bold]',
    HINT_ANIMATION: 'アニメーションタグでテキストに動きを付ける<br>例: [pulse]強調テキスト[/pulse]',

    // Visual Profile
    VISUAL_PROFILE_SECTION: '表示プロファイル',
    VISUAL_PROFILE_CUSTOM: 'カスタム（個別設定）',
    VISUAL_PROFILE_STANDARD: 'ライト',
    VISUAL_PROFILE_FOCUS_DARK: 'ダーク',
    VISUAL_PROFILE_BLANK_LIGHT: 'ライト（余白広め）'
};
