name: E2E

on:
  pull_request:
  push:
    branches:
      - main
      - develop
      - 'feat/**'
      - 'test/**'
  workflow_dispatch:

jobs:
  e2e:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'
      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            playwright-${{ runner.os }}-
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
      - name: Run E2E tests
        run: npx playwright test --reporter=line,html
      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          if-no-files-found: ignore
      - name: Setup Pages
        if: ${{ always() && github.event_name == 'pull_request' }}
        uses: actions/configure-pages@v5
      - name: Upload report to Pages artifact
        if: ${{ always() && github.event_name == 'pull_request' }}
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'playwright-report'
      - name: Deploy report to GitHub Pages (PR Preview)
        if: ${{ always() && github.event_name == 'pull_request' }}
        id: deployment
        uses: actions/deploy-pages@v4
      - name: Print report preview URL
        if: ${{ always() && github.event_name == 'pull_request' }}
        env:
          REPORT_URL: ${{ steps.deployment.outputs.page_url }}
        run: |
          echo "E2E report preview: ${REPORT_URL}"
